In [1]:
import numpy as np
arr=np.array([1,5,3])
arr

array([1, 5, 3])

In [2]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [6]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [7]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [8]:
myarr.shape

(4, 3)

In [9]:
reshaped = myarr.reshape((3,4))

In [10]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
myarr.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
myarr.flatten

<function ndarray.flatten>

In [14]:
flat=myarr.flatten()

In [15]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
flat[0]

np.int64(1)

In [17]:
flat[:6]

array([1, 2, 3, 4, 5, 6])

In [18]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
b=flat[3:7].copy()

In [20]:
b

array([4, 5, 6, 7])

In [21]:
b[0]=444444

In [22]:
b

array([444444,      5,      6,      7])

In [23]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
arr=np.array([1,53,23,53,2,3,34,5,6])

In [25]:
arr[[1,4,6]]

array([53,  2, 34])

In [26]:
mask=arr>7

In [27]:
arr[mask]

array([53, 23, 53, 34])

In [28]:
arr.reshape((3,3))

array([[ 1, 53, 23],
       [53,  2,  3],
       [34,  5,  6]])



MULTIdiMENSIONAL ARRAY



In [38]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
arr[0]

array([1, 2, 3])

In [44]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [45]:
arr[0][1]

np.int64(2)

In [46]:
arr[0,1]

np.int64(2)

In [48]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [50]:
arr.dtype

dtype('int64')

In [51]:
arr1=np.array([1,2,3,4,5])

In [52]:
arr1.dtype

dtype('int64')

In [53]:
arr1.astype("float64")

array([1., 2., 3., 4., 5.])

In [54]:
arr.nbytes

72

In [55]:
arr1.nbytes

40