In [4]:
import numpy as np
arr=np.array([3,5,2,33])

In [5]:
np.mean(arr)

np.float64(10.75)

In [6]:
np.min(arr)

np.int64(2)

In [7]:
np.std(arr)

np.float64(12.891373084353738)

In [9]:
np.var(arr)

np.float64(166.1875)

In [10]:
np.sum(arr)

np.int64(43)

In [11]:
np.cumsum(arr)

array([ 3,  8, 10, 43])

In [12]:
np.argmax(arr) #index

np.int64(3)

In [14]:
np.unique(arr)

array([ 2,  3,  5, 33])

In [15]:
np.exp(arr)

array([2.00855369e+01, 1.48413159e+02, 7.38905610e+00, 2.14643580e+14])